.TH XYES 1 2020-02-25 xyes
.SH NAME
xyes \- repeatedly print a string in an X window
.SH SYNOPSIS
.B xyes
[\fIstring\fR]
.SH DESCRIPTION
\fBxyes\fR displays an X window and repeatedly prints the given \fIstring\fR
into it. If no \fIstring\fR is specified, the character "y" is printed.
.SH ENVIRONMENT
.TP
DISPLAY
Specifies the X server to use.
.SH SEE ALSO
.BR yes (1),
.BR xman (1),
.BR xmore (1)
